### ISSUE TITLE
Update Design Pages and Routing

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#13]
## User stories

As user I want to see a clear structure of pages and routing. 

## ToDos
- [x] Create home page with default information
- [x] Create home button in navbar
- [x] Check the page design for good user experience
- [x] Review Header
- [x] Review BoxStart
