### ISSUE TITLE
MongoDB - Create GET Route to searchBar

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#29]
## User stories

As user I want to get results by searching the name of recycling stuff

## ToDos

- [x] Create fetch
- [x] Create route
- [x] Show all at search page
- [x] Show results at page search results
- [x] Add header with name of result
