### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#36]
## User stories

As user I want to understand the buttons and inputfields without any further description. 

As developer I have to check the user experience by clicking through the app.

## ToDos
- [x] Delete icon at list item at the the box details
- [x] Fix Header and Nav - (visibility by scrolling)
- [x] Add smaller gap between search results
- [x] Change size of nav icon to equal width
- [ ] Change position of "neuer Eintrag" at boxes
- [x] Change size and color of placeholder
- [ ] Set Display Grid to cards on Home Page
