### ISSUE TITLE
Go back button

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#39]
## User stories
As user I want to go one level back / up.

## ToDos
- [ ] Create component backbutton
- [ ] Add button on page search results
- [ ] Add button an page box/:title
