### ISSUE TITLE
Add global styling

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#4]
## ToDos

- [x] import fonts
- [x] set variables for colors
- [x] import global style in storybook
- [x] import global style in app.js
