### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#41]
## User stories
As user I don't want to set a new item or box without any value.

## Links
https://www.w3resource.com/javascript/form/non-empty-field.php

## ToDos
- [ ] write function for validation: if input.length = 0 -> user message
- [ ] add function at page new box
- [ ] add function at page exist for new item
