### ISSUE TITLE
Update page home with new card components

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#43]
## User stories
As user I want to get an overview at the page home

## ToDos
- [x] Create card with overview of boxes
- [x] Create card with overview of tasks
- [x] create card with allover information about reuse, reduce, recycle
