### ISSUE TITLE
Add functionality to Boxes

### ISSUE THREAD

**Issue by Frenzy265** [Frenzy265/recycle#8]
## User stories

As user I want to create a new Box and set some items in it.

## ToDos

- [x] install JSON server and fill with basic inforamtion
- [x] Create new box on click by creating a new Page to set all information
- [ ] Create new items on the box
- [x] Show all items in the box
- [x] Add delete function at box
